// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: AC_controller

#ifndef _AC_CONTROLLER_UI_H
#define _AC_CONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void SnoozeAnimation_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_RootPanel1;
extern lv_obj_t * ui_Wifi1;
extern lv_obj_t * ui_Defrost;
void ui_event_FanIU(lv_event_t * e);
extern lv_obj_t * ui_FanIU;
extern lv_obj_t * ui_FanIULabel;
void ui_event_VanesLRPanel(lv_event_t * e);
extern lv_obj_t * ui_VanesLRPanel;
extern lv_obj_t * ui_Vanes;
extern lv_obj_t * ui_VanesLM;
extern lv_obj_t * ui_VanesMR;
extern lv_obj_t * ui_VanesLR;
extern lv_obj_t * ui_VanesLL;
extern lv_obj_t * ui_VanesRL;
extern lv_obj_t * ui_VanesRR;
extern lv_obj_t * ui_VanesLRSwing;
void ui_event_VanesUDPanel(lv_event_t * e);
extern lv_obj_t * ui_VanesUDPanel;
extern lv_obj_t * ui_VanesUD;
extern lv_obj_t * ui_VanesMiddle;
extern lv_obj_t * ui_VanesDeep;
extern lv_obj_t * ui_VanesDeepest;
extern lv_obj_t * ui_VanesUnknown;
extern lv_obj_t * ui_VanesSwing;
extern lv_obj_t * ui_Panel3D;
extern lv_obj_t * ui_Label3Dauto;
void ui_event_PanelWatt(lv_event_t * e);
extern lv_obj_t * ui_PanelWatt;
extern lv_obj_t * ui_ImageWatt;
extern lv_obj_t * ui_LabelWatt;
extern lv_obj_t * ui_LabelkWh;
extern lv_obj_t * ui_OutdoorTemperature;
extern lv_obj_t * ui_OutdoorTemperatureLabel;
extern lv_obj_t * ui_PagePanel1;
extern lv_obj_t * ui_PreviousPage1;
void ui_event_NextPage1(lv_event_t * e);
extern lv_obj_t * ui_NextPage1;
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_SetpointPanel;
extern lv_obj_t * ui_CurrentTempNeedle;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_SetpointArc;
extern lv_obj_t * ui_LabelDegrees;
extern lv_obj_t * ui_PanelSetpointArrows1;
void ui_event_SetpointArrowUp1(lv_event_t * e);
extern lv_obj_t * ui_SetpointArrowUp1;
void ui_event_SetpointArrowDown1(lv_event_t * e);
extern lv_obj_t * ui_SetpointArrowDown1;
extern lv_obj_t * ui_SetpointCelsius;
void ui_event_CurrentTempCelsius(lv_event_t * e);
extern lv_obj_t * ui_CurrentTempCelsius;
extern lv_obj_t * ui_PanelOnOffModeFan;
void ui_event_AcSwitchOnOff(lv_event_t * e);
extern lv_obj_t * ui_AcSwitchOnOff;
extern lv_obj_t * ui_LabelOnOff;
void ui_event_ModeSelect(lv_event_t * e);
extern lv_obj_t * ui_ModeSelect;
extern lv_obj_t * ui_LabelMode;
void ui_event_FanSelect(lv_event_t * e);
extern lv_obj_t * ui_FanSelect;
extern lv_obj_t * ui_LabelFan;
// SCREEN: ui_Graph1Screen
void ui_Graph1Screen_screen_init(void);
extern lv_obj_t * ui_Graph1Screen;
extern lv_obj_t * ui_RootPanel2;
extern lv_obj_t * ui_Wifi2;
extern lv_obj_t * ui_PagePanel2;
void ui_event_PreviousPage2(lv_event_t * e);
extern lv_obj_t * ui_PreviousPage2;
void ui_event_NextPage2(lv_event_t * e);
extern lv_obj_t * ui_NextPage2;
void ui_event_Home2(lv_event_t * e);
extern lv_obj_t * ui_Home2;
extern lv_obj_t * ui_ChartCurrentTemp;
extern lv_obj_t * ui_ChartCompressor;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Graph2Screen
void ui_Graph2Screen_screen_init(void);
extern lv_obj_t * ui_Graph2Screen;
extern lv_obj_t * ui_RootPanel5;
extern lv_obj_t * ui_Wifi5;
extern lv_obj_t * ui_PagePanel5;
void ui_event_PreviousPage5(lv_event_t * e);
extern lv_obj_t * ui_PreviousPage5;
void ui_event_NextPage5(lv_event_t * e);
extern lv_obj_t * ui_NextPage5;
void ui_event_Home1(lv_event_t * e);
extern lv_obj_t * ui_Home1;
extern lv_obj_t * ui_ChartFanIU;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Graph3Screen
void ui_Graph3Screen_screen_init(void);
extern lv_obj_t * ui_Graph3Screen;
extern lv_obj_t * ui_RootPanel3;
extern lv_obj_t * ui_Wifi3;
extern lv_obj_t * ui_PagePanel3;
void ui_event_PreviousPage3(lv_event_t * e);
extern lv_obj_t * ui_PreviousPage3;
void ui_event_NextPage3(lv_event_t * e);
extern lv_obj_t * ui_NextPage3;
void ui_event_Home3(lv_event_t * e);
extern lv_obj_t * ui_Home3;
extern lv_obj_t * ui_ChartWatt;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_RootPanel4;
extern lv_obj_t * ui_Wifi4;
extern lv_obj_t * ui_PagePanel4;
void ui_event_PreviousPage4(lv_event_t * e);
extern lv_obj_t * ui_PreviousPage4;
void ui_event_NextPage4(lv_event_t * e);
extern lv_obj_t * ui_NextPage4;
void ui_event_Home4(lv_event_t * e);
extern lv_obj_t * ui_Home4;
extern lv_obj_t * ui_PanelVanes1;
void ui_event_Auto3DOnOff1(lv_event_t * e);
extern lv_obj_t * ui_Auto3DOnOff1;
extern lv_obj_t * ui_LabelOnOff3;
void ui_event_VaneSelect1(lv_event_t * e);
extern lv_obj_t * ui_VaneSelect1;
extern lv_obj_t * ui_LabelMode3;
void ui_event_VaneLRSelect1(lv_event_t * e);
extern lv_obj_t * ui_VaneLRSelect1;
extern lv_obj_t * ui_LabelFan3;
void ui_event_AutoControlOnOff(lv_event_t * e);
extern lv_obj_t * ui_AutoControlOnOff;
extern lv_obj_t * ui_LabelOnOff1;
void ui_event_LabelExplain(lv_event_t * e);
extern lv_obj_t * ui_LabelExplain;
void ui_event_RestartButton(lv_event_t * e);
extern lv_obj_t * ui_RestartButton;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TextAreaAutoControl;
extern lv_obj_t * ui_PanelBrightness;
void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_Label6;
void ui_event_SnoozeOnOff(lv_event_t * e);
extern lv_obj_t * ui_SnoozeOnOff;
extern lv_obj_t * ui_LabelSnooze;
// SCREEN: ui_SnoozeScreen
void ui_SnoozeScreen_screen_init(void);
void ui_event_SnoozeScreen(lv_event_t * e);
extern lv_obj_t * ui_SnoozeScreen;
void ui_event_RootPanel6(lv_event_t * e);
extern lv_obj_t * ui_RootPanel6;
extern lv_obj_t * ui_SnoozePanelBall;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets\icn_wifi.png
LV_IMG_DECLARE(ui_img_defrost_png);    // assets\defrost.png
LV_IMG_DECLARE(ui_img_fan_png);    // assets\fan.png
LV_IMG_DECLARE(ui_img_vanesmm_png);    // assets\vanesMM.png
LV_IMG_DECLARE(ui_img_vaneslm_png);    // assets\vanesLM.png
LV_IMG_DECLARE(ui_img_vanesmr_png);    // assets\vanesMR.png
LV_IMG_DECLARE(ui_img_vaneslr_png);    // assets\vanesLR.png
LV_IMG_DECLARE(ui_img_vanesll_png);    // assets\vanesLL.png
LV_IMG_DECLARE(ui_img_vanesrl_png);    // assets\vanesRL.png
LV_IMG_DECLARE(ui_img_vanesrr_png);    // assets\vanesRR.png
LV_IMG_DECLARE(ui_img_vaneslrswing_png);    // assets\vanesLRSwing.png
LV_IMG_DECLARE(ui_img_vaneshigh_png);    // assets\vanesHigh.png
LV_IMG_DECLARE(ui_img_vanesmiddle_png);    // assets\vanesMiddle.png
LV_IMG_DECLARE(ui_img_vanesdeep_png);    // assets\vanesDeep.png
LV_IMG_DECLARE(ui_img_vanesdeepest_png);    // assets\vanesDeepest.png
LV_IMG_DECLARE(ui_img_vanesunknown_png);    // assets\vanesUnknown.png
LV_IMG_DECLARE(ui_img_vanesswing_png);    // assets\vanesSwing.png
LV_IMG_DECLARE(ui_img_current_png);    // assets\current.png
LV_IMG_DECLARE(ui_img_thermometer24_png);    // assets\thermometer24.png
LV_IMG_DECLARE(ui_img_arrow_left_png);    // assets\arrow_left.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets\arrow_right.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets\settings.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets\clockwise_sec.png
LV_IMG_DECLARE(ui_img_meter_png);    // assets\Meter.png
LV_IMG_DECLARE(ui_img_arrow_up_png);    // assets\arrow_up.png
LV_IMG_DECLARE(ui_img_arrow_down_png);    // assets\arrow_down.png
LV_IMG_DECLARE(ui_img_home_png);    // assets\home.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
