// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: AC_controller

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ResetSnooze(lv_event_t * e);
void setSetpointUp(lv_event_t * e);
void setSetpointDown(lv_event_t * e);
void SwitchACOnOff(lv_event_t * e);
void SetModeAC(lv_event_t * e);
void SetFanAC(lv_event_t * e);
void Switch3DautoOnOff(lv_event_t * e);
void SetVaneAC(lv_event_t * e);
void SetVaneLRAC(lv_event_t * e);
void SwitchAutocontrolOnOff(lv_event_t * e);
void RestartESP(lv_event_t * e);
void setBrightness(lv_event_t * e);
void SwitchSnoozeOnOff(lv_event_t * e);
void StopAnimation(lv_event_t * e);
void SnoozeScreenClicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
