// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: AC_controller

#include "ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HomeScreen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RootPanel1 = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_RootPanel1, lv_pct(100));
    lv_obj_set_height(ui_RootPanel1, lv_pct(100));
    lv_obj_set_align(ui_RootPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel1, lv_color_hex(0x239BB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel1, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RootPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RootPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi1 = lv_img_create(ui_RootPanel1);
    lv_img_set_src(ui_Wifi1, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_Wifi1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi1, -138);
    lv_obj_set_y(ui_Wifi1, -223);
    lv_obj_set_align(ui_Wifi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifi1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wifi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Wifi1, lv_color_hex(0x04F924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Wifi1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Defrost = lv_img_create(ui_RootPanel1);
    lv_img_set_src(ui_Defrost, &ui_img_defrost_png);
    lv_obj_set_width(ui_Defrost, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Defrost, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Defrost, -106);
    lv_obj_set_y(ui_Defrost, -9);
    lv_obj_set_align(ui_Defrost, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Defrost, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Defrost, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FanIU = lv_img_create(ui_RootPanel1);
    lv_img_set_src(ui_FanIU, &ui_img_fan_png);
    lv_obj_set_width(ui_FanIU, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_FanIU, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_FanIU, -74);
    lv_obj_set_y(ui_FanIU, -9);
    lv_obj_set_align(ui_FanIU, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_FanIU, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FanIU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_FanIU, 300);
    lv_obj_set_style_img_recolor(ui_FanIU, lv_color_hex(0x190FE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_FanIU, 220, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanIULabel = lv_label_create(ui_FanIU);
    lv_obj_set_width(ui_FanIULabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanIULabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FanIULabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_FanIULabel, "0");
    lv_obj_set_style_text_color(ui_FanIULabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanIULabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VanesLRPanel = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_VanesLRPanel, 39);
    lv_obj_set_height(ui_VanesLRPanel, 21);
    lv_obj_set_x(ui_VanesLRPanel, -32);
    lv_obj_set_y(ui_VanesLRPanel, -9);
    lv_obj_set_align(ui_VanesLRPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_VanesLRPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VanesLRPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VanesLRPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VanesLRPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VanesLRPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vanes = lv_img_create(ui_VanesLRPanel);
    lv_img_set_src(ui_Vanes, &ui_img_vanesmm_png);
    lv_obj_set_width(ui_Vanes, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_Vanes, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_Vanes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Vanes, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Vanes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Vanes, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Vanes, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VanesLM = lv_img_create(ui_VanesLRPanel);
    lv_img_set_src(ui_VanesLM, &ui_img_vaneslm_png);
    lv_obj_set_width(ui_VanesLM, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesLM, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesLM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesLM, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesLM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesMR = lv_img_create(ui_VanesLRPanel);
    lv_img_set_src(ui_VanesMR, &ui_img_vanesmr_png);
    lv_obj_set_width(ui_VanesMR, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesMR, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesMR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesMR, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesMR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesLR = lv_img_create(ui_VanesLRPanel);
    lv_img_set_src(ui_VanesLR, &ui_img_vaneslr_png);
    lv_obj_set_width(ui_VanesLR, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesLR, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesLR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesLR, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesLR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesLL = lv_img_create(ui_VanesLRPanel);
    lv_img_set_src(ui_VanesLL, &ui_img_vanesll_png);
    lv_obj_set_width(ui_VanesLL, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesLL, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesLL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesLL, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesLL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesRL = lv_img_create(ui_VanesLRPanel);
    lv_img_set_src(ui_VanesRL, &ui_img_vanesrl_png);
    lv_obj_set_width(ui_VanesRL, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesRL, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesRL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesRL, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesRL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesRR = lv_img_create(ui_VanesLRPanel);
    lv_img_set_src(ui_VanesRR, &ui_img_vanesrr_png);
    lv_obj_set_width(ui_VanesRR, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesRR, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesRR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesRR, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesRR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesLRSwing = lv_img_create(ui_VanesLRPanel);
    lv_img_set_src(ui_VanesLRSwing, &ui_img_vaneslrswing_png);
    lv_obj_set_width(ui_VanesLRSwing, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesLRSwing, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesLRSwing, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesLRSwing, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesLRSwing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesUDPanel = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_VanesUDPanel, 25);
    lv_obj_set_height(ui_VanesUDPanel, 21);
    lv_obj_set_x(ui_VanesUDPanel, 6);
    lv_obj_set_y(ui_VanesUDPanel, -9);
    lv_obj_set_align(ui_VanesUDPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_VanesUDPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VanesUDPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VanesUDPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VanesUDPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VanesUDPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VanesUD = lv_img_create(ui_VanesUDPanel);
    lv_img_set_src(ui_VanesUD, &ui_img_vaneshigh_png);
    lv_obj_set_width(ui_VanesUD, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesUD, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesUD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesUD, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesUD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_VanesUD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_VanesUD, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VanesMiddle = lv_img_create(ui_VanesUDPanel);
    lv_img_set_src(ui_VanesMiddle, &ui_img_vanesmiddle_png);
    lv_obj_set_width(ui_VanesMiddle, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesMiddle, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesMiddle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesMiddle, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesMiddle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesDeep = lv_img_create(ui_VanesUDPanel);
    lv_img_set_src(ui_VanesDeep, &ui_img_vanesdeep_png);
    lv_obj_set_width(ui_VanesDeep, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesDeep, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesDeep, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesDeep, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesDeep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesDeepest = lv_img_create(ui_VanesUDPanel);
    lv_img_set_src(ui_VanesDeepest, &ui_img_vanesdeepest_png);
    lv_obj_set_width(ui_VanesDeepest, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesDeepest, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesDeepest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesDeepest, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesDeepest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesUnknown = lv_img_create(ui_VanesUDPanel);
    lv_img_set_src(ui_VanesUnknown, &ui_img_vanesunknown_png);
    lv_obj_set_width(ui_VanesUnknown, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesUnknown, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesUnknown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesUnknown, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesUnknown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VanesSwing = lv_img_create(ui_VanesUDPanel);
    lv_img_set_src(ui_VanesSwing, &ui_img_vanesswing_png);
    lv_obj_set_width(ui_VanesSwing, LV_SIZE_CONTENT);   /// 39
    lv_obj_set_height(ui_VanesSwing, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_align(ui_VanesSwing, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VanesSwing, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VanesSwing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3D = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_Panel3D, 55);
    lv_obj_set_height(ui_Panel3D, 21);
    lv_obj_set_x(ui_Panel3D, 45);
    lv_obj_set_y(ui_Panel3D, -9);
    lv_obj_set_align(ui_Panel3D, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel3D, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3D, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3D, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3Dauto = lv_label_create(ui_Panel3D);
    lv_obj_set_width(ui_Label3Dauto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3Dauto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3Dauto, 2);
    lv_obj_set_y(ui_Label3Dauto, 0);
    lv_obj_set_align(ui_Label3Dauto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3Dauto, "3Dauto");
    lv_obj_set_style_text_color(ui_Label3Dauto, lv_color_hex(0xCECECE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3Dauto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWatt = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_PanelWatt, 140);
    lv_obj_set_height(ui_PanelWatt, 40);
    lv_obj_set_x(ui_PanelWatt, -11);
    lv_obj_set_y(ui_PanelWatt, 0);
    lv_obj_set_align(ui_PanelWatt, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_PanelWatt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWatt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWatt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelWatt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelWatt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWatt = lv_img_create(ui_PanelWatt);
    lv_img_set_src(ui_ImageWatt, &ui_img_current_png);
    lv_obj_set_width(ui_ImageWatt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWatt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWatt, -15);
    lv_obj_set_y(ui_ImageWatt, 0);
    lv_obj_set_align(ui_ImageWatt, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageWatt, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWatt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageWatt, lv_color_hex(0xE0F005), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageWatt, 250, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWatt = lv_label_create(ui_PanelWatt);
    lv_obj_set_width(ui_LabelWatt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWatt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWatt, 10);
    lv_obj_set_y(ui_LabelWatt, -10);
    lv_label_set_text(ui_LabelWatt, "1200 W");
    lv_obj_set_style_text_color(ui_LabelWatt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWatt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelkWh = lv_label_create(ui_PanelWatt);
    lv_obj_set_width(ui_LabelkWh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelkWh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelkWh, 10);
    lv_obj_set_y(ui_LabelkWh, 8);
    lv_obj_set_align(ui_LabelkWh, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelkWh, "00,00 kWh");
    lv_obj_set_style_text_color(ui_LabelkWh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelkWh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OutdoorTemperature = lv_img_create(ui_RootPanel1);
    lv_img_set_src(ui_OutdoorTemperature, &ui_img_thermometer24_png);
    lv_obj_set_width(ui_OutdoorTemperature, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_OutdoorTemperature, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_OutdoorTemperature, 9);
    lv_obj_set_y(ui_OutdoorTemperature, -9);
    lv_obj_set_align(ui_OutdoorTemperature, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_OutdoorTemperature, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OutdoorTemperature, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OutdoorTemperatureLabel = lv_label_create(ui_RootPanel1);
    lv_obj_set_width(ui_OutdoorTemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OutdoorTemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OutdoorTemperatureLabel, 9);
    lv_obj_set_y(ui_OutdoorTemperatureLabel, 18);
    lv_obj_set_align(ui_OutdoorTemperatureLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_OutdoorTemperatureLabel, "12.0");
    lv_obj_set_style_text_color(ui_OutdoorTemperatureLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OutdoorTemperatureLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PagePanel1 = lv_obj_create(ui_RootPanel1);
    lv_obj_set_height(ui_PagePanel1, 50);
    lv_obj_set_width(ui_PagePanel1, lv_pct(100));
    lv_obj_set_align(ui_PagePanel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PagePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PagePanel1, lv_color_hex(0x0F08F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PagePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PagePanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PagePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PreviousPage1 = lv_img_create(ui_PagePanel1);
    lv_img_set_src(ui_PreviousPage1, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_PreviousPage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PreviousPage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PreviousPage1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PreviousPage1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PreviousPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_PreviousPage1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_PreviousPage1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextPage1 = lv_img_create(ui_PagePanel1);
    lv_img_set_src(ui_NextPage1, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_NextPage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextPage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextPage1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_NextPage1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NextPage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_NextPage1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_NextPage1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings = lv_img_create(ui_PagePanel1);
    lv_img_set_src(ui_Settings, &ui_img_settings_png);
    lv_obj_set_width(ui_Settings, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Settings, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetpointPanel = lv_obj_create(ui_RootPanel1);
    lv_obj_set_width(ui_SetpointPanel, 300);
    lv_obj_set_height(ui_SetpointPanel, 321);
    lv_obj_set_x(ui_SetpointPanel, 0);
    lv_obj_set_y(ui_SetpointPanel, 20);
    lv_obj_set_align(ui_SetpointPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SetpointPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetpointPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetpointPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetpointPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetpointPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentTempNeedle = lv_img_create(ui_SetpointPanel);
    lv_img_set_src(ui_CurrentTempNeedle, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_CurrentTempNeedle, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_CurrentTempNeedle, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_CurrentTempNeedle, 1);
    lv_obj_set_y(ui_CurrentTempNeedle, -40);
    lv_obj_set_align(ui_CurrentTempNeedle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CurrentTempNeedle, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CurrentTempNeedle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_CurrentTempNeedle, 15, 155);
    lv_img_set_angle(ui_CurrentTempNeedle, 150);
    lv_img_set_zoom(ui_CurrentTempNeedle, 160);
    lv_obj_set_style_img_recolor(ui_CurrentTempNeedle, lv_color_hex(0x0D34F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_CurrentTempNeedle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_SetpointPanel);
    lv_img_set_src(ui_Image2, &ui_img_meter_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetpointArc = lv_arc_create(ui_SetpointPanel);
    lv_obj_set_width(ui_SetpointArc, 281);
    lv_obj_set_height(ui_SetpointArc, 270);
    lv_obj_set_x(ui_SetpointArc, 5);
    lv_obj_set_y(ui_SetpointArc, 30);
    lv_obj_set_align(ui_SetpointArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SetpointArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_SetpointArc, 36, 60);
    lv_arc_set_value(ui_SetpointArc, 48);
    lv_arc_set_bg_angles(ui_SetpointArc, 150, 30);

    lv_obj_set_style_arc_color(ui_SetpointArc, lv_color_hex(0xF7052A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SetpointArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SetpointArc, lv_color_hex(0x47C65F), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetpointArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelDegrees = lv_label_create(ui_SetpointPanel);
    lv_obj_set_width(ui_LabelDegrees, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDegrees, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDegrees, 0);
    lv_obj_set_y(ui_LabelDegrees, -40);
    lv_obj_set_align(ui_LabelDegrees, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelDegrees, "°C");
    lv_obj_set_style_text_color(ui_LabelDegrees, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDegrees, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDegrees, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetpointArrows1 = lv_obj_create(ui_SetpointPanel);
    lv_obj_set_width(ui_PanelSetpointArrows1, lv_pct(67));
    lv_obj_set_height(ui_PanelSetpointArrows1, lv_pct(18));
    lv_obj_set_x(ui_PanelSetpointArrows1, 0);
    lv_obj_set_y(ui_PanelSetpointArrows1, 15);
    lv_obj_set_align(ui_PanelSetpointArrows1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PanelSetpointArrows1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSetpointArrows1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetpointArrows1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSetpointArrows1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetpointArrowUp1 = lv_img_create(ui_PanelSetpointArrows1);
    lv_img_set_src(ui_SetpointArrowUp1, &ui_img_arrow_up_png);
    lv_obj_set_width(ui_SetpointArrowUp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetpointArrowUp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetpointArrowUp1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_SetpointArrowUp1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SetpointArrowUp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetpointArrowUp1, lv_color_hex(0x848484), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetpointArrowUp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetpointArrowDown1 = lv_img_create(ui_PanelSetpointArrows1);
    lv_img_set_src(ui_SetpointArrowDown1, &ui_img_arrow_down_png);
    lv_obj_set_width(ui_SetpointArrowDown1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetpointArrowDown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetpointArrowDown1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_SetpointArrowDown1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SetpointArrowDown1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetpointArrowDown1, lv_color_hex(0x848484), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetpointArrowDown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetpointCelsius = lv_label_create(ui_PanelSetpointArrows1);
    lv_obj_set_width(ui_SetpointCelsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetpointCelsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetpointCelsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetpointCelsius, "24.0");
    lv_obj_set_style_text_color(ui_SetpointCelsius, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetpointCelsius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetpointCelsius, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentTempCelsius = lv_label_create(ui_SetpointPanel);
    lv_obj_set_width(ui_CurrentTempCelsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentTempCelsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentTempCelsius, 0);
    lv_obj_set_y(ui_CurrentTempCelsius, 30);
    lv_obj_set_align(ui_CurrentTempCelsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentTempCelsius, "24.75");
    lv_obj_add_flag(ui_CurrentTempCelsius, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_CurrentTempCelsius, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentTempCelsius, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentTempCelsius, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelOnOffModeFan = lv_obj_create(ui_RootPanel1);
    lv_obj_set_height(ui_PanelOnOffModeFan, 75);
    lv_obj_set_width(ui_PanelOnOffModeFan, lv_pct(108));
    lv_obj_set_x(ui_PanelOnOffModeFan, -1);
    lv_obj_set_y(ui_PanelOnOffModeFan, -130);
    lv_obj_set_align(ui_PanelOnOffModeFan, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelOnOffModeFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelOnOffModeFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelOnOffModeFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelOnOffModeFan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelOnOffModeFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AcSwitchOnOff = lv_switch_create(ui_PanelOnOffModeFan);
    lv_obj_set_width(ui_AcSwitchOnOff, 50);
    lv_obj_set_height(ui_AcSwitchOnOff, 25);
    lv_obj_set_align(ui_AcSwitchOnOff, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_AcSwitchOnOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AcSwitchOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AcSwitchOnOff, lv_color_hex(0xAFAFAF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_AcSwitchOnOff, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_AcSwitchOnOff, lv_color_hex(0x707070), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AcSwitchOnOff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AcSwitchOnOff, lv_color_hex(0x39B04B), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_AcSwitchOnOff, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_LabelOnOff = lv_label_create(ui_PanelOnOffModeFan);
    lv_obj_set_width(ui_LabelOnOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOnOff, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOnOff, 0);
    lv_obj_set_y(ui_LabelOnOff, -28);
    lv_obj_set_align(ui_LabelOnOff, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelOnOff, "Off/On");
    lv_obj_set_style_text_color(ui_LabelOnOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOnOff, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModeSelect = lv_dropdown_create(ui_PanelOnOffModeFan);
    lv_dropdown_set_dir(ui_ModeSelect, LV_DIR_TOP);
    lv_dropdown_set_options(ui_ModeSelect, "Auto\nCool\nHeat\nDry\nFan");
    lv_obj_set_width(ui_ModeSelect, 78);
    lv_obj_set_height(ui_ModeSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ModeSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ModeSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_ModeSelect, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ModeSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ModeSelect, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ModeSelect, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_LabelMode = lv_label_create(ui_PanelOnOffModeFan);
    lv_obj_set_width(ui_LabelMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMode, 0);
    lv_obj_set_y(ui_LabelMode, -28);
    lv_obj_set_align(ui_LabelMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMode, "Mode");
    lv_obj_set_style_text_color(ui_LabelMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanSelect = lv_dropdown_create(ui_PanelOnOffModeFan);
    lv_dropdown_set_options(ui_FanSelect, "Auto\n1\n2\n3\n4");
    lv_obj_set_width(ui_FanSelect, 86);
    lv_obj_set_height(ui_FanSelect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FanSelect, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_FanSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_FanSelect, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanSelect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LabelFan = lv_label_create(ui_PanelOnOffModeFan);
    lv_obj_set_width(ui_LabelFan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFan, -33);
    lv_obj_set_y(ui_LabelFan, -28);
    lv_obj_set_align(ui_LabelFan, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelFan, "Fan");
    lv_obj_set_style_text_color(ui_LabelFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_FanIU, ui_event_FanIU, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VanesLRPanel, ui_event_VanesLRPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VanesUDPanel, ui_event_VanesUDPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelWatt, ui_event_PanelWatt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextPage1, ui_event_NextPage1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetpointArrowUp1, ui_event_SetpointArrowUp1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetpointArrowDown1, ui_event_SetpointArrowDown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CurrentTempCelsius, ui_event_CurrentTempCelsius, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AcSwitchOnOff, ui_event_AcSwitchOnOff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModeSelect, ui_event_ModeSelect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FanSelect, ui_event_FanSelect, LV_EVENT_ALL, NULL);

}
