// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: AC_controller

#include "ui.h"

void ui_SnoozeScreen_screen_init(void)
{
    ui_SnoozeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SnoozeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SnoozeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnoozeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SnoozeScreen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RootPanel6 = lv_obj_create(ui_SnoozeScreen);
    lv_obj_set_width(ui_RootPanel6, lv_pct(100));
    lv_obj_set_height(ui_RootPanel6, lv_pct(100));
    lv_obj_set_align(ui_RootPanel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel6, lv_color_hex(0x239BB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RootPanel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RootPanel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnoozePanelBall = lv_obj_create(ui_SnoozeScreen);
    lv_obj_set_width(ui_SnoozePanelBall, 5);
    lv_obj_set_height(ui_SnoozePanelBall, 5);
    lv_obj_set_x(ui_SnoozePanelBall, 10);
    lv_obj_set_y(ui_SnoozePanelBall, -20);
    lv_obj_set_align(ui_SnoozePanelBall, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_SnoozePanelBall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SnoozePanelBall, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnoozePanelBall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SnoozePanelBall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SnoozePanelBall, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RootPanel6, ui_event_RootPanel6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SnoozeScreen, ui_event_SnoozeScreen, LV_EVENT_ALL, NULL);

}
