// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: AC_controller

#include "ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SettingsScreen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RootPanel4 = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_RootPanel4, lv_pct(100));
    lv_obj_set_height(ui_RootPanel4, lv_pct(100));
    lv_obj_set_align(ui_RootPanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel4, lv_color_hex(0x239BB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel4, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RootPanel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RootPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi4 = lv_img_create(ui_RootPanel4);
    lv_img_set_src(ui_Wifi4, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_Wifi4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi4, -138);
    lv_obj_set_y(ui_Wifi4, -223);
    lv_obj_set_align(ui_Wifi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifi4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wifi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Wifi4, lv_color_hex(0x04F924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Wifi4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PagePanel4 = lv_obj_create(ui_RootPanel4);
    lv_obj_set_height(ui_PagePanel4, 50);
    lv_obj_set_width(ui_PagePanel4, lv_pct(100));
    lv_obj_set_align(ui_PagePanel4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PagePanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PagePanel4, lv_color_hex(0x0F08F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PagePanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PagePanel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PagePanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PreviousPage4 = lv_img_create(ui_PagePanel4);
    lv_img_set_src(ui_PreviousPage4, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_PreviousPage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PreviousPage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PreviousPage4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PreviousPage4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PreviousPage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_PreviousPage4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_PreviousPage4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextPage4 = lv_img_create(ui_PagePanel4);
    lv_img_set_src(ui_NextPage4, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_NextPage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextPage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextPage4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_NextPage4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NextPage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_NextPage4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_NextPage4, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home4 = lv_img_create(ui_PagePanel4);
    lv_img_set_src(ui_Home4, &ui_img_home_png);
    lv_obj_set_width(ui_Home4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Home4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Home4, 1);
    lv_obj_set_y(ui_Home4, 0);
    lv_obj_set_align(ui_Home4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelVanes1 = lv_obj_create(ui_RootPanel4);
    lv_obj_set_height(ui_PanelVanes1, 187);
    lv_obj_set_width(ui_PanelVanes1, lv_pct(106));
    lv_obj_set_x(ui_PanelVanes1, -3);
    lv_obj_set_y(ui_PanelVanes1, -130);
    lv_obj_set_align(ui_PanelVanes1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelVanes1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelVanes1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelVanes1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelVanes1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelVanes1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Auto3DOnOff1 = lv_switch_create(ui_PanelVanes1);
    lv_obj_set_width(ui_Auto3DOnOff1, 50);
    lv_obj_set_height(ui_Auto3DOnOff1, 25);
    lv_obj_set_x(ui_Auto3DOnOff1, 0);
    lv_obj_set_y(ui_Auto3DOnOff1, 20);
    lv_obj_set_style_bg_color(ui_Auto3DOnOff1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Auto3DOnOff1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Auto3DOnOff1, lv_color_hex(0xAFAFAF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Auto3DOnOff1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Auto3DOnOff1, lv_color_hex(0x707070), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Auto3DOnOff1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Auto3DOnOff1, lv_color_hex(0x39B04B), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Auto3DOnOff1, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_LabelOnOff3 = lv_label_create(ui_PanelVanes1);
    lv_obj_set_width(ui_LabelOnOff3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOnOff3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelOnOff3, "3Dauto");
    lv_obj_set_style_text_color(ui_LabelOnOff3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOnOff3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOnOff3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VaneSelect1 = lv_dropdown_create(ui_PanelVanes1);
    lv_dropdown_set_dir(ui_VaneSelect1, LV_DIR_TOP);
    lv_dropdown_set_options(ui_VaneSelect1, "High\nMiddle\nDeep\nDeepest\nSwing\n");
    lv_obj_set_width(ui_VaneSelect1, 100);
    lv_obj_set_height(ui_VaneSelect1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VaneSelect1, 0);
    lv_obj_set_y(ui_VaneSelect1, 70);
    lv_obj_add_flag(ui_VaneSelect1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_VaneSelect1, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VaneSelect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_VaneSelect1, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VaneSelect1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_LabelMode3 = lv_label_create(ui_PanelVanes1);
    lv_obj_set_width(ui_LabelMode3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMode3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMode3, 0);
    lv_obj_set_y(ui_LabelMode3, 50);
    lv_label_set_text(ui_LabelMode3, "Vane");
    lv_obj_set_style_text_color(ui_LabelMode3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMode3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VaneLRSelect1 = lv_dropdown_create(ui_PanelVanes1);
    lv_dropdown_set_options(ui_VaneLRSelect1,
                            "Left-Left\nLeft-Middle\nMiddle-Middle\nMiddle-Right\nRight-Right\nLeft-Right\nRight-Left\nSwing");
    lv_obj_set_width(ui_VaneLRSelect1, 140);
    lv_obj_set_height(ui_VaneLRSelect1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VaneLRSelect1, 140);
    lv_obj_set_y(ui_VaneLRSelect1, 70);
    lv_obj_add_flag(ui_VaneLRSelect1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_VaneLRSelect1, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VaneLRSelect1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LabelFan3 = lv_label_create(ui_PanelVanes1);
    lv_obj_set_width(ui_LabelFan3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFan3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFan3, 140);
    lv_obj_set_y(ui_LabelFan3, 50);
    lv_label_set_text(ui_LabelFan3, "VaneLR");
    lv_obj_set_style_text_color(ui_LabelFan3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFan3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoControlOnOff = lv_switch_create(ui_PanelVanes1);
    lv_obj_set_width(ui_AutoControlOnOff, 50);
    lv_obj_set_height(ui_AutoControlOnOff, 25);
    lv_obj_set_x(ui_AutoControlOnOff, 140);
    lv_obj_set_y(ui_AutoControlOnOff, 20);
    lv_obj_set_style_bg_color(ui_AutoControlOnOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AutoControlOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AutoControlOnOff, lv_color_hex(0xAFAFAF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_AutoControlOnOff, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_AutoControlOnOff, lv_color_hex(0x707070), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AutoControlOnOff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AutoControlOnOff, lv_color_hex(0x39B04B), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_AutoControlOnOff, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_LabelOnOff1 = lv_label_create(ui_PanelVanes1);
    lv_obj_set_width(ui_LabelOnOff1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOnOff1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOnOff1, 140);
    lv_obj_set_y(ui_LabelOnOff1, 0);
    lv_label_set_text(ui_LabelOnOff1, "Autocontrol");
    lv_obj_set_style_text_color(ui_LabelOnOff1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOnOff1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOnOff1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelExplain = lv_label_create(ui_PanelVanes1);
    lv_obj_set_width(ui_LabelExplain, lv_pct(11));
    lv_obj_set_height(ui_LabelExplain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelExplain, 235);
    lv_obj_set_y(ui_LabelExplain, -3);
    lv_label_set_text(ui_LabelExplain, "(?)");
    lv_obj_add_flag(ui_LabelExplain, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_LabelExplain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelExplain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelExplain, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RestartButton = lv_btn_create(ui_PanelVanes1);
    lv_obj_set_width(ui_RestartButton, 165);
    lv_obj_set_height(ui_RestartButton, 25);
    lv_obj_set_x(ui_RestartButton, 0);
    lv_obj_set_y(ui_RestartButton, 130);
    lv_obj_add_flag(ui_RestartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RestartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RestartButton, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RestartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_RestartButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Restart AC controller");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaAutoControl = lv_textarea_create(ui_RootPanel4);
    lv_obj_set_width(ui_TextAreaAutoControl, 169);
    lv_obj_set_height(ui_TextAreaAutoControl, 143);
    lv_obj_set_x(ui_TextAreaAutoControl, 69);
    lv_obj_set_y(ui_TextAreaAutoControl, -73);
    lv_obj_set_align(ui_TextAreaAutoControl, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextAreaAutoControl,
                         "When AC fan=Auto and fanspeed <=6 then fanspeed will be adjusted to 3 bars. This is not visible on the remote control");
    lv_textarea_set_placeholder_text(ui_TextAreaAutoControl, "Placeholder...");
    lv_obj_add_flag(ui_TextAreaAutoControl, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TextAreaAutoControl, LV_OBJ_FLAG_CLICKABLE);      /// Flags



    ui_PanelBrightness = lv_obj_create(ui_RootPanel4);
    lv_obj_set_width(ui_PanelBrightness, 321);
    lv_obj_set_height(ui_PanelBrightness, 59);
    lv_obj_set_x(ui_PanelBrightness, -20);
    lv_obj_set_y(ui_PanelBrightness, 200);
    lv_obj_clear_flag(ui_PanelBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelBrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderBrightness = lv_slider_create(ui_PanelBrightness);
    lv_slider_set_range(ui_SliderBrightness, 1, 255);
    lv_slider_set_value(ui_SliderBrightness, 140, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness, 150);
    lv_obj_set_height(ui_SliderBrightness, 10);
    lv_obj_set_x(ui_SliderBrightness, 0);
    lv_obj_set_y(ui_SliderBrightness, 7);
    lv_obj_set_align(ui_SliderBrightness, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderBrightness, lv_color_hex(0x1E242D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0x37B9F5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderBrightness, lv_color_hex(0x1464F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderBrightness, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0x5F6464), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SliderBrightness, lv_color_hex(0x3C424B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SliderBrightness, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderBrightness, lv_color_hex(0x373C46), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderBrightness, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderBrightness, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SliderBrightness, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SliderBrightness, 150, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SliderBrightness, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SliderBrightness, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderBrightness, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderBrightness, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderBrightness, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderBrightness, 5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_PanelBrightness);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -15);
    lv_label_set_text(ui_Label6, "Brightness display");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SnoozeOnOff = lv_switch_create(ui_PanelBrightness);
    lv_obj_set_width(ui_SnoozeOnOff, 50);
    lv_obj_set_height(ui_SnoozeOnOff, 25);
    lv_obj_set_x(ui_SnoozeOnOff, 180);
    lv_obj_set_y(ui_SnoozeOnOff, 7);
    lv_obj_set_style_bg_color(ui_SnoozeOnOff, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnoozeOnOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SnoozeOnOff, lv_color_hex(0xAFAFAF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SnoozeOnOff, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_SnoozeOnOff, lv_color_hex(0x707070), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SnoozeOnOff, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SnoozeOnOff, lv_color_hex(0x39B04B), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SnoozeOnOff, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_LabelSnooze = lv_label_create(ui_PanelBrightness);
    lv_obj_set_width(ui_LabelSnooze, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSnooze, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSnooze, 180);
    lv_obj_set_y(ui_LabelSnooze, -16);
    lv_label_set_text(ui_LabelSnooze, "Snooze display");
    lv_obj_set_style_text_color(ui_LabelSnooze, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSnooze, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSnooze, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PreviousPage4, ui_event_PreviousPage4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextPage4, ui_event_NextPage4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home4, ui_event_Home4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Auto3DOnOff1, ui_event_Auto3DOnOff1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VaneSelect1, ui_event_VaneSelect1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VaneLRSelect1, ui_event_VaneLRSelect1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AutoControlOnOff, ui_event_AutoControlOnOff, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelExplain, ui_event_LabelExplain, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RestartButton, ui_event_RestartButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SnoozeOnOff, ui_event_SnoozeOnOff, LV_EVENT_ALL, NULL);

}
