// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: AC_controller

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void SnoozeAnimation_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
lv_obj_t * ui_RootPanel1;
lv_obj_t * ui_Wifi1;
lv_obj_t * ui_Defrost;
void ui_event_FanIU(lv_event_t * e);
lv_obj_t * ui_FanIU;
lv_obj_t * ui_FanIULabel;
void ui_event_VanesLRPanel(lv_event_t * e);
lv_obj_t * ui_VanesLRPanel;
lv_obj_t * ui_Vanes;
lv_obj_t * ui_VanesLM;
lv_obj_t * ui_VanesMR;
lv_obj_t * ui_VanesLR;
lv_obj_t * ui_VanesLL;
lv_obj_t * ui_VanesRL;
lv_obj_t * ui_VanesRR;
lv_obj_t * ui_VanesLRSwing;
void ui_event_VanesUDPanel(lv_event_t * e);
lv_obj_t * ui_VanesUDPanel;
lv_obj_t * ui_VanesUD;
lv_obj_t * ui_VanesMiddle;
lv_obj_t * ui_VanesDeep;
lv_obj_t * ui_VanesDeepest;
lv_obj_t * ui_VanesUnknown;
lv_obj_t * ui_VanesSwing;
lv_obj_t * ui_Panel3D;
lv_obj_t * ui_Label3Dauto;
void ui_event_PanelWatt(lv_event_t * e);
lv_obj_t * ui_PanelWatt;
lv_obj_t * ui_ImageWatt;
lv_obj_t * ui_LabelWatt;
lv_obj_t * ui_LabelkWh;
lv_obj_t * ui_OutdoorTemperature;
lv_obj_t * ui_OutdoorTemperatureLabel;
lv_obj_t * ui_PagePanel1;
lv_obj_t * ui_PreviousPage1;
void ui_event_NextPage1(lv_event_t * e);
lv_obj_t * ui_NextPage1;
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
lv_obj_t * ui_SetpointPanel;
lv_obj_t * ui_CurrentTempNeedle;
lv_obj_t * ui_Image2;
lv_obj_t * ui_SetpointArc;
lv_obj_t * ui_LabelDegrees;
lv_obj_t * ui_PanelSetpointArrows1;
void ui_event_SetpointArrowUp1(lv_event_t * e);
lv_obj_t * ui_SetpointArrowUp1;
void ui_event_SetpointArrowDown1(lv_event_t * e);
lv_obj_t * ui_SetpointArrowDown1;
lv_obj_t * ui_SetpointCelsius;
void ui_event_CurrentTempCelsius(lv_event_t * e);
lv_obj_t * ui_CurrentTempCelsius;
lv_obj_t * ui_PanelOnOffModeFan;
void ui_event_AcSwitchOnOff(lv_event_t * e);
lv_obj_t * ui_AcSwitchOnOff;
lv_obj_t * ui_LabelOnOff;
void ui_event_ModeSelect(lv_event_t * e);
lv_obj_t * ui_ModeSelect;
lv_obj_t * ui_LabelMode;
void ui_event_FanSelect(lv_event_t * e);
lv_obj_t * ui_FanSelect;
lv_obj_t * ui_LabelFan;


// SCREEN: ui_Graph1Screen
void ui_Graph1Screen_screen_init(void);
lv_obj_t * ui_Graph1Screen;
lv_obj_t * ui_RootPanel2;
lv_obj_t * ui_Wifi2;
lv_obj_t * ui_PagePanel2;
void ui_event_PreviousPage2(lv_event_t * e);
lv_obj_t * ui_PreviousPage2;
void ui_event_NextPage2(lv_event_t * e);
lv_obj_t * ui_NextPage2;
void ui_event_Home2(lv_event_t * e);
lv_obj_t * ui_Home2;
lv_obj_t * ui_ChartCurrentTemp;
lv_obj_t * ui_ChartCompressor;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label1;


// SCREEN: ui_Graph2Screen
void ui_Graph2Screen_screen_init(void);
lv_obj_t * ui_Graph2Screen;
lv_obj_t * ui_RootPanel5;
lv_obj_t * ui_Wifi5;
lv_obj_t * ui_PagePanel5;
void ui_event_PreviousPage5(lv_event_t * e);
lv_obj_t * ui_PreviousPage5;
void ui_event_NextPage5(lv_event_t * e);
lv_obj_t * ui_NextPage5;
void ui_event_Home1(lv_event_t * e);
lv_obj_t * ui_Home1;
lv_obj_t * ui_ChartFanIU;
lv_obj_t * ui_Label7;


// SCREEN: ui_Graph3Screen
void ui_Graph3Screen_screen_init(void);
lv_obj_t * ui_Graph3Screen;
lv_obj_t * ui_RootPanel3;
lv_obj_t * ui_Wifi3;
lv_obj_t * ui_PagePanel3;
void ui_event_PreviousPage3(lv_event_t * e);
lv_obj_t * ui_PreviousPage3;
void ui_event_NextPage3(lv_event_t * e);
lv_obj_t * ui_NextPage3;
void ui_event_Home3(lv_event_t * e);
lv_obj_t * ui_Home3;
lv_obj_t * ui_ChartWatt;
lv_obj_t * ui_Label4;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_RootPanel4;
lv_obj_t * ui_Wifi4;
lv_obj_t * ui_PagePanel4;
void ui_event_PreviousPage4(lv_event_t * e);
lv_obj_t * ui_PreviousPage4;
void ui_event_NextPage4(lv_event_t * e);
lv_obj_t * ui_NextPage4;
void ui_event_Home4(lv_event_t * e);
lv_obj_t * ui_Home4;
lv_obj_t * ui_PanelVanes1;
void ui_event_Auto3DOnOff1(lv_event_t * e);
lv_obj_t * ui_Auto3DOnOff1;
lv_obj_t * ui_LabelOnOff3;
void ui_event_VaneSelect1(lv_event_t * e);
lv_obj_t * ui_VaneSelect1;
lv_obj_t * ui_LabelMode3;
void ui_event_VaneLRSelect1(lv_event_t * e);
lv_obj_t * ui_VaneLRSelect1;
lv_obj_t * ui_LabelFan3;
void ui_event_AutoControlOnOff(lv_event_t * e);
lv_obj_t * ui_AutoControlOnOff;
lv_obj_t * ui_LabelOnOff1;
void ui_event_LabelExplain(lv_event_t * e);
lv_obj_t * ui_LabelExplain;
void ui_event_RestartButton(lv_event_t * e);
lv_obj_t * ui_RestartButton;
lv_obj_t * ui_Label3;
lv_obj_t * ui_TextAreaAutoControl;
lv_obj_t * ui_PanelBrightness;
void ui_event_SliderBrightness(lv_event_t * e);
lv_obj_t * ui_SliderBrightness;
lv_obj_t * ui_Label6;
void ui_event_SnoozeOnOff(lv_event_t * e);
lv_obj_t * ui_SnoozeOnOff;
lv_obj_t * ui_LabelSnooze;


// SCREEN: ui_SnoozeScreen
void ui_SnoozeScreen_screen_init(void);
void ui_event_SnoozeScreen(lv_event_t * e);
lv_obj_t * ui_SnoozeScreen;
void ui_event_RootPanel6(lv_event_t * e);
lv_obj_t * ui_RootPanel6;
lv_obj_t * ui_SnoozePanelBall;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_thermometer[1] = {&ui_img_thermometer24_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void SnoozeAnimation_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 20000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 10, 290);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 20000);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 20000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_1, 290, 10);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 20000);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 20000);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_FanIU(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph2Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph2Screen_screen_init);
    }
}
void ui_event_VanesLRPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_VanesUDPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_PanelWatt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph3Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph3Screen_screen_init);
    }
}
void ui_event_NextPage1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph1Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph1Screen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_SetpointArrowUp1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setSetpointUp(e);
        ResetSnooze(e);
    }
}
void ui_event_SetpointArrowDown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setSetpointDown(e);
        ResetSnooze(e);
    }
}
void ui_event_CurrentTempCelsius(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph1Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph1Screen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_AcSwitchOnOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SwitchACOnOff(e);
        ResetSnooze(e);
    }
}
void ui_event_ModeSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetModeAC(e);
        ResetSnooze(e);
    }
}
void ui_event_FanSelect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetFanAC(e);
        ResetSnooze(e);
    }
}
void ui_event_PreviousPage2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_NextPage2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph2Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph2Screen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_Home2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_PreviousPage5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph1Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph1Screen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_NextPage5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph3Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph3Screen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_Home1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_PreviousPage3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph2Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph2Screen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_NextPage3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_Home3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_PreviousPage4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph3Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph3Screen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_NextPage4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graph1Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Graph1Screen_screen_init);
    }
}
void ui_event_Home4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        ResetSnooze(e);
    }
}
void ui_event_Auto3DOnOff1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        Switch3DautoOnOff(e);
    }
}
void ui_event_VaneSelect1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetVaneAC(e);
    }
}
void ui_event_VaneLRSelect1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetVaneLRAC(e);
    }
}
void ui_event_AutoControlOnOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SwitchAutocontrolOnOff(e);
    }
}
void ui_event_LabelExplain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_TextAreaAutoControl, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_TextAreaAutoControl, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_RestartButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        RestartESP(e);
    }
}
void ui_event_SliderBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setBrightness(e);
    }
}
void ui_event_SnoozeOnOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SwitchSnoozeOnOff(e);
    }
}
void ui_event_SnoozeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        SnoozeAnimation_Animation(ui_SnoozePanelBall, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        StopAnimation(e);
    }
}
void ui_event_RootPanel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        SnoozeScreenClicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_Graph1Screen_screen_init();
    ui_Graph2Screen_screen_init();
    ui_Graph3Screen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_SnoozeScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomeScreen);
}
