// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: AC_controller

#include "ui.h"

void ui_Graph2Screen_screen_init(void)
{
    ui_Graph2Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Graph2Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Graph2Screen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Graph2Screen, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Graph2Screen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RootPanel5 = lv_obj_create(ui_Graph2Screen);
    lv_obj_set_width(ui_RootPanel5, lv_pct(100));
    lv_obj_set_height(ui_RootPanel5, lv_pct(100));
    lv_obj_set_align(ui_RootPanel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel5, lv_color_hex(0x239BB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel5, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RootPanel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RootPanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi5 = lv_img_create(ui_RootPanel5);
    lv_img_set_src(ui_Wifi5, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_Wifi5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi5, -138);
    lv_obj_set_y(ui_Wifi5, -223);
    lv_obj_set_align(ui_Wifi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifi5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wifi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Wifi5, lv_color_hex(0x04F924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Wifi5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PagePanel5 = lv_obj_create(ui_RootPanel5);
    lv_obj_set_height(ui_PagePanel5, 50);
    lv_obj_set_width(ui_PagePanel5, lv_pct(100));
    lv_obj_set_align(ui_PagePanel5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PagePanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PagePanel5, lv_color_hex(0x0F08F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PagePanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PagePanel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PagePanel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PreviousPage5 = lv_img_create(ui_PagePanel5);
    lv_img_set_src(ui_PreviousPage5, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_PreviousPage5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PreviousPage5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PreviousPage5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PreviousPage5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PreviousPage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_PreviousPage5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_PreviousPage5, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextPage5 = lv_img_create(ui_PagePanel5);
    lv_img_set_src(ui_NextPage5, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_NextPage5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextPage5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextPage5, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_NextPage5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NextPage5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_NextPage5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_NextPage5, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home1 = lv_img_create(ui_PagePanel5);
    lv_img_set_src(ui_Home1, &ui_img_home_png);
    lv_obj_set_width(ui_Home1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Home1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Home1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartFanIU = lv_chart_create(ui_RootPanel5);
    lv_obj_set_width(ui_ChartFanIU, 269);
    lv_obj_set_height(ui_ChartFanIU, 147);
    lv_obj_set_x(ui_ChartFanIU, 22);
    lv_obj_set_y(ui_ChartFanIU, 35);
    lv_obj_set_align(ui_ChartFanIU, LV_ALIGN_TOP_MID);
    lv_chart_set_type(ui_ChartFanIU, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartFanIU, 20);
    lv_chart_set_range(ui_ChartFanIU, LV_CHART_AXIS_PRIMARY_Y, 0, 8);
    lv_chart_set_range(ui_ChartFanIU, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartFanIU, 9, 6);
    lv_chart_set_axis_tick(ui_ChartFanIU, LV_CHART_AXIS_PRIMARY_X, 10, 5, 6, 1, true, 50);
    lv_chart_set_axis_tick(ui_ChartFanIU, LV_CHART_AXIS_PRIMARY_Y, 6, 4, 9, 1, true, 50);
    lv_chart_set_axis_tick(ui_ChartFanIU, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 0, 2, false, 25);



    lv_obj_set_style_text_color(ui_ChartFanIU, lv_color_hex(0xE8E8E8), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChartFanIU, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Graph2Screen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 7);
    lv_obj_set_y(ui_Label7, -200);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Fan speed Inner Unit");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PreviousPage5, ui_event_PreviousPage5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextPage5, ui_event_NextPage5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home1, ui_event_Home1, LV_EVENT_ALL, NULL);

}
