// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: AC_controller

#include "ui.h"

void ui_Graph1Screen_screen_init(void)
{
    ui_Graph1Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Graph1Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Graph1Screen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Graph1Screen, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Graph1Screen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RootPanel2 = lv_obj_create(ui_Graph1Screen);
    lv_obj_set_width(ui_RootPanel2, lv_pct(100));
    lv_obj_set_height(ui_RootPanel2, lv_pct(100));
    lv_obj_set_align(ui_RootPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RootPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RootPanel2, lv_color_hex(0x239BB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RootPanel2, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RootPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RootPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi2 = lv_img_create(ui_RootPanel2);
    lv_img_set_src(ui_Wifi2, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_Wifi2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifi2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifi2, -138);
    lv_obj_set_y(ui_Wifi2, -223);
    lv_obj_set_align(ui_Wifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifi2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Wifi2, lv_color_hex(0x04F924), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Wifi2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PagePanel2 = lv_obj_create(ui_RootPanel2);
    lv_obj_set_height(ui_PagePanel2, 50);
    lv_obj_set_width(ui_PagePanel2, lv_pct(100));
    lv_obj_set_align(ui_PagePanel2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PagePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PagePanel2, lv_color_hex(0x0F08F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PagePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PagePanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PagePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PreviousPage2 = lv_img_create(ui_PagePanel2);
    lv_img_set_src(ui_PreviousPage2, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_PreviousPage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PreviousPage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PreviousPage2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PreviousPage2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PreviousPage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_PreviousPage2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_PreviousPage2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextPage2 = lv_img_create(ui_PagePanel2);
    lv_img_set_src(ui_NextPage2, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_NextPage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NextPage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NextPage2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_NextPage2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NextPage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_NextPage2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_NextPage2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home2 = lv_img_create(ui_PagePanel2);
    lv_img_set_src(ui_Home2, &ui_img_home_png);
    lv_obj_set_width(ui_Home2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Home2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_align(ui_Home2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartCurrentTemp = lv_chart_create(ui_RootPanel2);
    lv_obj_set_width(ui_ChartCurrentTemp, 269);
    lv_obj_set_height(ui_ChartCurrentTemp, 147);
    lv_obj_set_x(ui_ChartCurrentTemp, 22);
    lv_obj_set_y(ui_ChartCurrentTemp, 35);
    lv_obj_set_align(ui_ChartCurrentTemp, LV_ALIGN_TOP_MID);
    lv_chart_set_type(ui_ChartCurrentTemp, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartCurrentTemp, 20);
    lv_chart_set_range(ui_ChartCurrentTemp, LV_CHART_AXIS_PRIMARY_Y, 1500, 3000);
    lv_chart_set_range(ui_ChartCurrentTemp, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartCurrentTemp, 11, 6);
    lv_chart_set_axis_tick(ui_ChartCurrentTemp, LV_CHART_AXIS_PRIMARY_X, 10, 5, 6, 1, true, 50);
    lv_chart_set_axis_tick(ui_ChartCurrentTemp, LV_CHART_AXIS_PRIMARY_Y, 6, 4, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartCurrentTemp, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 0, 2, false, 25);



    lv_obj_set_style_text_color(ui_ChartCurrentTemp, lv_color_hex(0xE8E8E8), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChartCurrentTemp, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_ChartCompressor = lv_chart_create(ui_RootPanel2);
    lv_obj_set_width(ui_ChartCompressor, 269);
    lv_obj_set_height(ui_ChartCompressor, 147);
    lv_obj_set_x(ui_ChartCompressor, 22);
    lv_obj_set_y(ui_ChartCompressor, 230);
    lv_obj_set_align(ui_ChartCompressor, LV_ALIGN_TOP_MID);
    lv_chart_set_type(ui_ChartCompressor, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartCompressor, 20);
    lv_chart_set_range(ui_ChartCompressor, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartCompressor, 11, 6);
    lv_chart_set_axis_tick(ui_ChartCompressor, LV_CHART_AXIS_PRIMARY_X, 10, 5, 6, 1, true, 50);
    lv_chart_set_axis_tick(ui_ChartCompressor, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartCompressor, LV_CHART_AXIS_SECONDARY_Y, 0, 5, 0, 2, false, 25);



    lv_obj_set_style_text_color(ui_ChartCompressor, lv_color_hex(0xE8E8E8), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChartCompressor, 255, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Graph1Screen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 4);
    lv_obj_set_y(ui_Label2, -4);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Compressor");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Graph1Screen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 7);
    lv_obj_set_y(ui_Label1, -200);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Current temperature");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PreviousPage2, ui_event_PreviousPage2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextPage2, ui_event_NextPage2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home2, ui_event_Home2, LV_EVENT_ALL, NULL);

}
